# Generated by Django 6.1.1 on 2026-09-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='atividades',
        ),
    ]
