# Generated by Django 6.1.1 on 2026-09-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_remove_aluno_atividades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='alunos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='atividades',
            field=models.ManyToManyField(blank=True, to='gestor.atividade'),
        ),
    ]
