# Generated by Django 6.1.1 on 2026-09-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_alter_aluno_options_alter_atividade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='atividades',
        ),
        migrations.AddField(
            model_name='atividade',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='atividades', to='gestor.aluno'),
        ),
    ]
