# Generated by Django 6.1.1 on 2026-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_remove_aluno_atividades_atividade_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
