# Generated by Django 6.1.1 on 2026-09-21 13:55
# and edited

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_alter_atividade_nome'),
    ]

    operations = [TrigramExtension(), UnaccentExtension()]
