# Generated by Django 6.1.1 on 2026-09-21 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_auto_20260921_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='RA_invalido', message='O RA deve estar no formato 00.00000-0.', regex='^\\d{2}\\.\\d{5}-\\d$')]),
        ),
    ]
